basePath: /api
host: localhost:8080
info:
  contact:
    email: benoit.fraysse@hotmail.com
    name: Benoit (WarexDev)
    url: https://github.com/WarexDev
  description: VaultLite is a lightweight secrets management API for secure storage
    and retrieval of secrets in cloud-native environments.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: https://github.com/WarexDev/vaultlite/blob/master/LICENSE
  title: VaultLite API
  version: "1.0"
paths:
  /api/health:
    get:
      description: Returns a simple OK status to verify the service is up and running
      produces:
      - application/json
      responses:
        "200":
          description: OK status
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Check the health status of the service
      tags:
      - health
  /api/login:
    post:
      description: Returns users infos on successful creation.
      produces:
      - application/json
      responses:
        "200":
          description: token
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Logging to an account to generate an api token
      tags:
      - auth
  /api/ping:
    get:
      description: Returns a simple pong status to verify the service is up and running
      produces:
      - application/json
      responses:
        "200":
          description: PONG status
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Ping the service
      tags:
      - health
  /api/register:
    post:
      description: Returns users infos on successful creation.
      produces:
      - application/json
      responses:
        "200":
          description: OK status
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Register a new account to the service
      tags:
      - auth
schemes:
- http
swagger: "2.0"
